### ISSUE TITLE
Rewriting 

### ISSUE THREAD

**Issue by jeed2424** [TomTasche/OpenDocument.ios#26]
(Felt like opening a new issue was better than commenting on another one)

I just wanted to let you know that I didn’t forget about your app, I was just caught up with other projects and I spent the last 5 hours rewriting the basic functionalities of the app (it should be up somewhere around 3pm tomorrow (ET) as I need to finish a few things and I’m going to bed). Simply put, TableView that displays the files imported in the app*, possibility to import files in the app* (obviously), possibility to delete files from the app* and, upon selection in the TableView, the requested file shows up. 
*it’s sandbox*

Step 2 would be to add functionalities such as the possibility to edit said files (shouldn’t be that hard to implement) and exporting (which is not hard at all and probably will be released with version 1.0)

**Comment by TomTasche** [comment]
Sounds good! Looking forward to see what you came up with.

Quick comment on adding functionality like editing: that is not so easy unfortunately since ODF (the format we are mainly targeting) is not straightforward to edit. We do plan to offer basic editing functionality in the future though, as we do for Android too.

**Comment by jeed2424** [comment]
I'm running a little late and the repo should be up in about an hour or so. Everything is set except for the "view file" functionality which should be running pretty soon. 

Yeah, I forgot about the editing of "non-native" files, which could become pretty tricky...

**Comment by jeed2424** [comment]
I'm a little disappointed in myself, but here's what I've got so far: https://github.com/jeed2424/prototype_ODR/

**Comment by TomTasche** [comment]
I had low expectations after you said you are disappointed, but wow that's great! I like the style (minimalistic) as it fits our style so far on Android too.

Two comments:
1. After choosing a file, they don't show up in the list of "imported files" for me?
2. I think we had this discussion before, but I'm still undecided if users would prefer the list view over the "Recents" tab offered by the standard UI. Maybe there's some UX forums we can ask for advice, or start a design competition on 99designs? (That's what I did on Android because I'm not a UX guru at all)

**Comment by jeed2424** [comment]
Thanks! I didn't think it needed a crazy design, but I think that a "slide menu" could be cool though...

For your comments: 

1: I was just about to comment that the folks on StackOverflow helped me resolve the "reloaddata" method and the file imported shows up directly after importing it now! 

2: I don't think we had this discussion (at least don't remember it) and I'm not sure I understand what you mean... By "standard ui" did you mean the "File Manager"?

**Comment by TomTasche** [comment]
Yes exactly, I was referring to the default file manager UI. My assumption was that this is what most iOS users are used to anyway, therefore it's more easily accessible for non-technical users too.

**Comment by jeed2424** [comment]
That’s the opposite, actually. Most files are not accessible to users even with the “File Manager”, so that’s why I think it’s better to use a table view (or its variations) or a custom user interface

**Comment by TomTasche** [comment]
Alright, go ahead then. 👍 If you want we can work on a mockup before implementing any design changes in order to save you some time. Whatever you prefer.

**Comment by jeed2424** [comment]
Yup, I think it's better to work on the basic functionalities before doing any design. It can just be added over the existing things after... 

Anyway, it took me about 10 hours of intense research, StackOverflow-ing and Reddit-ing to get the "delete" function to work, but not it does. Deletes both the row/cell and the file in the directory.

**Comment by jeed2424** [comment]
Will try to find some time today to work on displaying the file. Shouldn't be too long, it's pretty much the same thing as deleting, but you display it instead.
